# -*- coding: utf-8 -*-
from sqlalchemy import *

dbu = create_engine('sqlite:///users and clans.db')

conection = dbu.connect()
con = conection

metadata = MetaData()

Clan = Table('Clans', metadata,
             Column('id', Integer, primary_key=True),
             Column('owner_id', Integer),
             Column('name', Text),
             Column('users', Text),
             Column('base', Integer),
             Column('rating', Integer),
             Column('coffers', Integer),
             Column('wins', Integer),
             Column('loses', Integer),
             Column('coffers_history', Text),
             Column('knights', Integer),
             Column('archers', Integer),
             Column('balloons', Integer),
             Column('dragons', Integer),
             Column('power', Integer),
             Column('shield', Integer)
             )

User = Table('Users', metadata,
             Column('vk_id', Integer),
             Column('registrationdate', DateTime),
             Column('name', Text),
             Column('lasttimeusedbonus', DateTime),
             Column('money', Integer),
             Column('gb', Integer),
             Column('crowns', Integer),
             Column('clan_invites', Text),
             Column('clan', Text),
             Column('hairstyle', Text),
             Column('tattoo', Text),
             Column('head', Text),
             Column('tshort', Text),
             Column('costume', Text),
             Column('shoes', Text),
             Column('accessories', Text),
             Column('business', Text),
             Column('businessmoney', Integer),
             Column('businessupgrade', Boolean),
             Column('businessworkers', Integer),
             Column('businesslastsalary', DateTime),
             Column('asic', Integer),
             Column('dragonmintt1', Integer),
             Column('fm2018bt400', Integer),
             Column('genesis', Integer),
             Column('gigawatt', Integer),
             Column('gorilla', Integer),
             Column('lastsellingbtc', DateTime),
             Column('btc', Integer),
             Column('printer', Integer),
             Column('cartridge', Integer),
             Column('lasttakemoney', DateTime),
             Column('car', Text),
             Column('tires', Integer),
             Column('rims', Integer),
             Column('engine', Integer),
             Column('fueltank', Integer),
             Column('suspension', Integer),
             Column('brakes', Integer),
             Column('turbines', Integer),
             Column('control', Integer),
             Column('chip', Integer),
             Column('num', Text),
             Column('hp', Integer),
             Column('maxv', Integer),
             Column('do100', Float),
             Column('rr', Integer),
             Column('lastrace', DateTime),
             Column('power', Integer),
             Column('dmg', Integer),
             Column('lvl', Integer),
             Column('xp', Integer),
             Column('yacht', Text),
             Column('airplane', Text),
             Column('helicopter', Text),
             Column('home', Text),
             Column('pet', Text),
             Column('petlvl', Integer),
             Column('petsatiety', Integer),
             Column('petjoy', Integer),
             Column('petage', DateTime),
             Column('petlasthike', DateTime),
             Column('phone', Text),
             Column('pc', Text),
             Column('scase', Integer),
             Column('pcase', Integer),
             Column('dcase', Integer),
             Column('status', Text),
             Column('potion', Text),
             Column('energy', Integer),
             Column('iron', Integer),
             Column('gold', Integer),
             Column('diamonds', Integer),
             Column('matter', Integer),
             Column('antimatter', Integer),
             Column('one', Text),
             Column('two', Text),
             Column('three', Text),
             Column('four', Text),
             Column('five', Text),
             Column('six', Text),
             Column('seven', Text),
             Column('eight', Text),
             Column('nine', Text),
             Column('ten', Text),
             Column('eleven', Text),
             Column('tradewinstreek', Integer),
             Column('cupwinstreek', Integer),
             Column('casinowinstreek', Integer),
             Column('cubewinstreek', Integer),
             Column('businesspaymentval', Integer),
             Column('farmpaymentval', Integer),
             Column('caseopenval', Integer),
             Column('transfermoneyval', Integer),
             Column('racewinstreek', Integer),
             Column('lasthike', DateTime),
             Column('rank', Integer),
             Column('words', Integer),
             Column('word', Text),
             Column('randomword', Text),
             Column('pension', Integer),
             Column('lastpension', DateTime),
             Column('bank', Integer),
             Column('lastdive', DateTime),
             Column('lasthack', DateTime),
             Column('divelvl', Integer),
             Column('fish', Integer),
             Column('presidentbid', Integer),
             Column('energylimit', Integer),
             Column('lastpost', DateTime),
             Column('firstindouble', Boolean),
             Column('doublebonus', DateTime),
             Column('banned', DateTime),
             Column('numbers', Text)
             )
